---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - caldav_url is defined
      - notifications_service_endpoint is defined
      - username is defined
      - password is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    pull: true
    cleanup: true
    memory: "200MB"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}"
    networks:
      - name: "pomerium"
    env:
      CALDAV_URL: "{{ caldav_url }}"
      NOTIFICATIONS_SERVICE_ENDPOINT: "{{ notifications_service_endpoint }}"
      USERNAME: "{{ username }}"
      PASSWORD: "{{ password }}"
